hostNetwork: true

ports:
  web:
    port: 80
    hostPort: 80
  websecure:
    port: 443
    hostPort: 443

securityContext:
  capabilities:
    add: [NET_BIND_SERVICE]
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

additionalArguments:
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"

certificatesResolvers:
  letsencrypt:
    acme:
      email: tasos24gnr95@gmail.com
      storage: /data/acme.json
      tlsChallenge: {}

persistence:
  enabled: true
  size: 128Mi
  path: /data

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.36
      command: ["sh", "-c", "touch /data/acme.json && chmod 600 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /data

updateStrategy:
  type: Recreate

ingressRoute:
  dashboard:
    enabled: false
